=== LucaGrab/alt/src/folder/DLRG.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Mitglieder">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mitglied" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Daten">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element name="Anschrift">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:float" name="Postleitzahl"/>
                                                    <xs:element type="xs:string" name="Wohnort"/>
                                                    <xs:element type="xs:string" name="StraÃŸe"/>
                                                    <xs:element type="xs:string" name="Hausnummer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:date" name="Geburtstag"/>
                                        <xs:element type="xs:string" name="Email"/>
                                        <xs:element type="xs:date" name="Beitritsdatum"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Teilnehmer" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Kontaktperson" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="Name"/>
                                                    <xs:element type="xs:float" name="Telefonnummer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Abzeichen">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Schwimmen">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:date" name="Bronze" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Silber" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Gold" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Rettungsschwimmen" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:date" name="Rettungsschwimmerbronze" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Rettungsschwimmersilber" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Rettungsschwimmergold" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Lehrer" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Abzeichen">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:date" name="Rettungsschwimmerbronze" minOccurs="0"/>
                                                    <xs:element type="xs:date" name="Rettungsschwimmersilber" minOccurs="0"/>
                                                    <xs:element type="xs:date" name="Rettungsschwimmergold" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Lehrscheine">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Assistent">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:date" name="Schwimmassistent" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Rettungsschwimmassistent" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="Ausbilder">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element type="xs:date" name="Schwimmausbilder" minOccurs="0"/>
                                                                <xs:element type="xs:date" name="Rettungsschwimmausbilder" minOccurs="0"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="10"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute type="xs:string" name="Kategorie" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LucaGrab/alt/src/folder/DLRG.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="DLRG.xsl"?>
<Mitglieder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DLRG.xsd">
    <Mitglied Id="4" Kategorie="Teilnehmer">
        <Daten>
            <Name> Tim Miess </Name>
            <Anschrift>
                <Postleitzahl> 67574 </Postleitzahl>
                <Wohnort> Osthofen </Wohnort>
                <Straße> Lindenstraße </Straße>
                <Hausnummer> 5 </Hausnummer>
            </Anschrift>
            <Geburtstag> 2002-12-06</Geburtstag>
            <Email> tim@miess.com </Email>
            <Beitritsdatum> 2011-04-02 </Beitritsdatum>
        </Daten>
        <Teilnehmer>
            <Abzeichen>
                <Schwimmen>
                    <Bronze> 2012-12-07</Bronze>
                    <Silber> 2013-05-03 </Silber>
                    <Gold> 2014-02-13 </Gold>
                </Schwimmen>
                <Rettungsschwimmen>
                    <Rettungsschwimmerbronze> 2018-04-03</Rettungsschwimmerbronze>
                    <Rettungsschwimmersilber> 2020-02-11</Rettungsschwimmersilber>
                    <Rettungsschwimmergold> 2021-03-17</Rettungsschwimmergold>
                </Rettungsschwimmen>
            </Abzeichen>
        </Teilnehmer>
    </Mitglied>
    <Mitglied Id="3" Kategorie="Teilnehmer">
        <Daten>
            <Name> Max Mustermann </Name>
            <Anschrift>
                <Postleitzahl> 67574 </Postleitzahl>
                <Wohnort> Osthofen </Wohnort>
                <Straße> Schubertstraße </Straße>
                <Hausnummer> 2 </Hausnummer>
            </Anschrift>
            <Geburtstag> 2005-02-01</Geburtstag>
            <Email> max@mustermann.com </Email>
            <Beitritsdatum> 2010-03-06 </Beitritsdatum>
        </Daten>
        <Teilnehmer>
            <Kontaktperson>
                <Name> Mia Mustermann </Name>
                <Telefonnummer> 0151010110 </Telefonnummer>
            </Kontaktperson>
            <Abzeichen>
                <Schwimmen>
                    <Bronze> 2011-04-02</Bronze>
                    <Silber> 2012-03-17</Silber>
                </Schwimmen>
            </Abzeichen>
        </Teilnehmer>
    </Mitglied>

    <Mitglied Id="5" Kategorie="Teilnehmer">
        <Daten>
            <Name> Tom Bauer </Name>
            <Anschrift>
                <Postleitzahl> 67574 </Postleitzahl>
                <Wohnort> Osthofen </Wohnort>
                <Straße> Burgstraße </Straße>
                <Hausnummer> 4 </Hausnummer>
            </Anschrift>
            <Geburtstag> 2007-12-09</Geburtstag>
            <Email> tom@bauer.com </Email>
            <Beitritsdatum> 2012-05-03 </Beitritsdatum>
        </Daten>
        <Teilnehmer>
            <Kontaktperson>
                <Name> Stefan Bauer </Name>
                <Telefonnummer> 0151073468 </Telefonnummer>
            </Kontaktperson>
            <Abzeichen>
                <Schwimmen>
                    <Bronze> 2013-11-05</Bronze>
                    <Silber> 2014-07-01 </Silber>
                    <Gold> 2015-05-17 </Gold>
                </Schwimmen>
                <Rettungsschwimmen>
                    <Rettungsschwimmerbronze> 2020-04-03</Rettungsschwimmerbronze>
                    <Rettungsschwimmersilber> 2022-02-11</Rettungsschwimmersilber>
                </Rettungsschwimmen>
            </Abzeichen>
        </Teilnehmer>
    </Mitglied>
    <Mitglied Id="2" Kategorie="Lehrer">
        <Daten>
            <Name>Reiner Zufall</Name>
            <Anschrift>
                <Postleitzahl> 67574 </Postleitzahl>
                <Wohnort> Osthofen </Wohnort>
                <Straße> Grabenstraße </Straße>
                <Hausnummer> 7 </Hausnummer>
            </Anschrift>
            <Geburtstag> 1980-11-17</Geburtstag>
            <Email> reiner@zufall.com </Email>
            <Beitritsdatum> 2001-03-09 </Beitritsdatum>
        </Daten>
        <Lehrer>
                <Abzeichen>
                    <Rettungsschwimmerbronze> 2005-07-02</Rettungsschwimmerbronze>
                    <Rettungsschwimmersilber> 2007-06-03 </Rettungsschwimmersilber>
                    <Rettungsschwimmergold> 2008-05-02</Rettungsschwimmergold>
                </Abzeichen>
                <Lehrscheine>
                    <Assistent>
                        <Schwimmassistent> 2008-04-03</Schwimmassistent>
                        <Rettungsschwimmassistent> 2008-11-17</Rettungsschwimmassistent>
                    </Assistent>
                    <Ausbilder>
                        <Schwimmausbilder> 2009-02-15 </Schwimmausbilder>
                        <Rettungsschwimmausbilder> 2010-02-16 </Rettungsschwimmausbilder>
                    </Ausbilder>
                </Lehrscheine>
        </Lehrer>
    </Mitglied>
    <Mitglied Id="1" Kategorie="Lehrer">
        <Daten>
            <Name> Lina Müller </Name>
            <Anschrift>
                <Postleitzahl> 67574 </Postleitzahl>
                <Wohnort> Osthofen </Wohnort>
                <Straße> Birkenstraße </Straße>
                <Hausnummer> 11a </Hausnummer>
            </Anschrift>
            <Geburtstag> 1981-10-13</Geburtstag>
            <Email> steven@müller.com </Email>
            <Beitritsdatum> 2000-04-07 </Beitritsdatum>
        </Daten>
        <Lehrer>
            <Abzeichen>
                <Rettungsschwimmerbronze> 2006-08-17</Rettungsschwimmerbronze>
            </Abzeichen>
            <Lehrscheine>
                <Assistent>
                    <Schwimmassistent> 2007-07-05</Schwimmassistent>
                    <Rettungsschwimmassistent> 2009-07-14</Rettungsschwimmassistent>
                </Assistent>
                <Ausbilder>
                    <Schwimmausbilder> 2010-04-06 </Schwimmausbilder>
                </Ausbilder>
            </Lehrscheine>
        </Lehrer>
    </Mitglied>
</Mitglieder>
